name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: Run samples
      run: |
        cd StorageSharp.Samples
        dotnet run --configuration Release
    
  publish-nuget:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Pack NuGet Package
      run: dotnet pack StorageSharp/StorageSharp.csproj --configuration Release --output nupkgs
    
    - name: List generated packages
      run: ls -la nupkgs/
    
    - name: Check NuGet API Key
      run: |
        if [ -z "${{ secrets.NUGET_API_KEY }}" ]; then
          echo "Error: NUGET_API_KEY secret is not set"
          exit 1
        else
          echo "NuGet API Key is configured (length: ${#NUGET_API_KEY})"
        fi
    
    - name: Publish to NuGet
      run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json 